Detect if watchman is installed
zth/vscode-rescript-relay pull request #23
Opened 2021-09-04 16:50 UTC by mellson

I've tried to add detection of whether or not watchman is installed on the users system. I can verify that it works as intended on macOS, but haven't tested this on other operating systems.

If the extension detects that watchman is not installed it will show this popup:
<img width="465" alt="watchman error" src="https://user-images.githubusercontent.com/167574/132102289-e1acfbf8-a634-4584-ba5c-5866e87bf574.png">
With a link to the [install instructions](https://facebook.github.io/watchman/docs/install.html)

My prettier setup was eager to format and sort the installs, I've left it in there. But if you prefer not to have that I can revert those.

Fixes: #22

2021-09-08 18:01 UTC, zth requested changes
Great stuff, thank you! 😄  Just 2 minor things from my side.

2021-09-08 18:01 UTC, zth commented on src/extension.ts
> +import { featureEnabled, getPreferredFragmentPropName } from "./utils";
Could you please revert this reordering of the imports?

2021-09-08 18:01 UTC, zth commented on src/extension.ts
> +          .showErrorMessage("Error watchman not installed", installText)
Maybe make this a warning instead, and change the text to reflect that it's needed to be able to run the compiler automatically from the extension?

2021-09-08 19:51 UTC, mellson commented
> Great stuff, thank you! 😄 Just 2 minor things from my side.

Thanks, I've updated the with requested changes 👍🏻

2021-09-09 06:00 UTC, zth approved these changes
👏

2021-09-09 06:01 UTC, merged